### ISSUE TITLE
能做成Android APP吗

### ISSUE THREAD

**Issue by TellH** [ranulldd/NEIE-Assistant#1]

**Comment by TellH** [comment]
@ranulldd 我想做成app，但我不会VB。你能提供网络请求API吗

**Comment by ranulldd** [comment]
@TellH 这个我已经没心思再管了。自己看下源码，原理很简单的，就是模拟客户端发送加密的数据而已，没必要特地搞个API什么的。

**Comment by VincentCodes** [comment]
大神请问有最初的源码吗？java或者c++的？

**Comment by ranulldd** [comment]
@VincentCodes 这里的就是最初的源码
