### ISSUE TITLE
请问其中的加密解密是如何分析的

### ISSUE THREAD

**Issue by zhonghaoyu555** [ranulldd/NEIE-Assistant#2]
认真阅读了代码，但是对加密和解密部分不是很懂，这部分是如何得出的？

**Comment by ranulldd** [comment]
那部分不用在意，是从视听说的客户端那里逆向分析得到的，至于具体用的什么算法我当时也没时间去分析，只是把他的加解密的汇编代码改成VB的而已，用到的数据也是直接从那个客户端给扒下来的。

**Comment by ranulldd** [comment]
因为VB不支持无符号类型和位移操作，所以那部分看起来有点乱( ▼-▼ )。
