### ISSUE TITLE
关于网络请求分析

### ISSUE THREAD

**Issue by LiangYuxuan** [ranulldd/NEIE-Assistant#4]
您好！我们现在正在试图把这个这个项目用Python和C++重写，repo在[这里](https://github.com/LiangYuxuan/NEIE-Assistant/)。目前已经把encode和decode用C++实现了。想请问一下您现在还有没有关于这个系统的网络请求分析的记录，希望可以得到您的帮助。

**Comment by ranulldd** [comment]
> 您好！我们现在正在试图把这个这个项目用Python和C++重写，repo在[这里](https://github.com/LiangYuxuan/NEIE-Assistant/)。目前已经把encode和decode用C++实现了。想请问一下您现在还有没有关于这个系统的网络请求分析的记录，希望可以得到您的帮助。

目测你们已经不需要我的帮忙了，抱歉，一直没时间管这个项目，后续我也不会维护了。
我在我的项目里面也把你的项目连接附上去吧，毕竟VB已经不太流行（我也看不懂自己的代码了）。
